name: check-format-with-prettier
run-name: check-format-with-prettier
on: [pull_request]
jobs:
  check-format-with-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: npm run check-format
